### ISSUE TITLE
Warning about S3 method overwritten

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/crul#112]
I am getting the following message about S3 method since `R 3.6.0`-

``` r
library(httr)
library(crul)
#> Registered S3 method overwritten by 'crul':
#>   method                 from
#>   as.character.form_file httr
#> 
#> Attaching package: 'crul'
#> The following object is masked from 'package:httr':
#> 
#>     handle
```

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                                    
#>  version  R version 3.6.0 alpha (2019-03-29 r76300)
#>  os       Windows 10 x64                           
#>  system   x86_64, mingw32                          
#>  ui       RTerm                                    
#>  language (EN)                                     
#>  collate  English_United States.1252               
#>  ctype    English_United States.1252               
#>  tz       America/New_York                         
#>  date     2019-06-28                               
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       lib source                        
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                
#>  backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)                
#>  callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                
#>  cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                
#>  crul        * 0.8.0      2019-06-28 [1] CRAN (R 3.6.0)                
#>  curl          3.3        2019-01-10 [1] CRAN (R 3.6.0)                
#>  desc          1.2.0      2019-04-03 [1] Github (r-lib/desc@c860e7b)   
#>  devtools      2.0.2      2019-04-08 [1] CRAN (R 3.6.0)                
#>  digest        0.6.19     2019-05-20 [1] CRAN (R 3.6.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                
#>  httpcode      0.2.0      2016-11-14 [1] CRAN (R 3.5.2)                
#>  httr        * 1.4.0      2018-12-11 [1] CRAN (R 3.6.0)                
#>  knitr         1.23       2019-05-18 [1] CRAN (R 3.6.0)                
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                
#>  pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.0)                
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                
#>  processx      3.3.1      2019-05-08 [1] CRAN (R 3.6.0)                
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                
#>  R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                
#>  Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.6.0)                
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                
#>  rlang         0.4.0      2019-06-25 [1] CRAN (R 3.6.0)                
#>  rmarkdown     1.13       2019-05-22 [1] CRAN (R 3.6.0)                
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                
#>  stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                
#>  testthat      2.1.1      2019-04-23 [1] CRAN (R 3.6.0)                
#>  usethis       1.5.0.9000 2019-06-24 [1] Github (r-lib/usethis@d4eabb9)
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                
#>  xfun          0.8        2019-06-25 [1] CRAN (R 3.6.0)                
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.0alpha/library
```

</details>

**Comment by sckott** [comment]
thanks. i also noticed that. i figured it's not a deal breaker, but I should probably address this. I thought it'd be good to name some things the same for consistency but of course that has the disadvantage that there can be namespace conflicts when both pkgs are loaded

**Comment by dpprdan** [comment]
FYI this also happens if one loads {vcr} with R >= 3.6.0 (presumably because both {crul} and {httr} are Imports?)

``` r
library(vcr)
#> Registered S3 method overwritten by 'httr':
#>   method                 from
#>   as.character.form_file crul
#> Loading required namespace: jsonlite
```

Does the `Loading required namespace: jsonlite` mean that {jsonlite} should be in Imports rather than Suggests?

**Comment by sckott** [comment]
thanks @dpprdan 

you're right, there is one usage of `jsonlite` in the package https://github.com/ropensci/crul/blob/master/R/body.R#L77 so we should move jsonlite to Imports. I'll do that. 

For the overwritten warning, I'll have a play and see if I can safely change the name of `as.character.form_file`

**Comment by sckott** [comment]
Okay, `as.character.form_file` is not exported now, so that warning should go away. 

However, there is still `crul::handle` and `httr::handle` as a conflict if you're using both packages. Would this be a problem for either of you?  It's easy enough to namespace fxn calls, but maybe some users may not know how to do that

**Comment by dpprdan** [comment]
Looks good to me. I still get the `Loading required namespace: jsonlite` with `library(vcr)`, though, presumably because of [this line](https://github.com/ropensci/vcr/blob/228d388fa3cd57c7c791146cf9325a59a25c4459/R/request_matcher_registry.R#L69)? So better move jsonlite to imports there as well? (It is in crul's and httr's imports anyway, so it's not possible to have vcr installed and not jsonlite, correct?)

**Comment by sckott** [comment]
yes, but https://github.com/ropensci/vcr/blob/master/R/request_matcher_registry.R#L63-L65 - we check that jsonlite is installed 

correct, httr and crul import jsonlite. so the user does need jsonlite in the end. 

Seems the message in the end stems from the `requireNamespace` call in vcr. i'm setting `quietly=TRUE`  in that call which suppresses that message. jsonlite is still loaded though, the namespace not loaded but the package is loaded after `library(vcr)`

this will change as soon as I get around to implementing JSON as another option for storing cassettes in addition to YAML - as we'll def. need jsonlite then

**Comment by sckott** [comment]
changes in this commit ropensci/vcr@cd4164751ef6830f63d614712a6df3553ea741d3

**Comment by dpprdan** [comment]
👍 I saw the check and wondered why it apparently was working (with respect to the message). Thought it might be due to R6 or something, i.e. I did not notice the missing `quietly = TRUE`. But now I know why that is important. 😄

**Comment by sckott** [comment]
i'm going to have to undo the change to `as.character.form_file` - not exporting it is causing `upload` to fail in some cases. we're stuck with the `form_file` part, because httr and crul are both using `curl::form_file` under the hood, and anyway `as.character.form_file` from httr and crul are extactly the same, so it shouldn't matter which is used

**Comment by dpprdan** [comment]
Would it make sense to ask Jeroen to add the `as.character.form_file` method in curl, since curl owns the class, and then import from there? 
A (suboptimal) workaround could be to import `as.character.form_file` from httr if `requireNamespace` and define it here otherwise?

**Comment by sckott** [comment]
i don't think he'd do that. I'm trying to pinpoint where the fxn is needed exactly - which should help determine what we can do about it

**Comment by aoles** [comment]
Hi,

Any news here? 

Even though my package [openrouteservice](https://github.com/GIScience/openrouteservice-r) doesn't directly depend on crul I still get the warning.

Cheers,
Andrzej
```
> library(openrouteservice)
Registered S3 method overwritten by 'httr':
  method                 from
  as.character.form_file crul
```

**Comment by sckott** [comment]
i'm asking @jeroen about this, we'll see

**Comment by jeroen** [comment]
I still don't understand why this method is needed. It doesn't seem to do anything?

https://github.com/ropensci/crul/blob/b32505e9fe427cd80957f1aa6ca956c6b514fbc0/R/upload.R#L13-L14

Why do you need to `as.character()` it?

**Comment by sckott** [comment]
last time I checked, i tried removing `as.character.form_file` form the pkg, or just not exporting it, and that caused errors, i imagine that's the same case with httr

**Comment by sckott** [comment]
i don't know exactly why though

**Comment by jeroen** [comment]
What sort of errors? In which function? It doesn't seem to do anything 🤷‍♂

**Comment by sckott** [comment]
i don't remember now, above https://github.com/ropensci/crul/issues/112#issuecomment-517814657 I thought it was causing problems, but I forgot to record what that was, looking

**Comment by sckott** [comment]
@jeroen If i remove `as.character.form_file` from exports in crul, then reinstall, i get this:

```r
library(crul)
x <- HttpClient$new(url = "https://httpbin.org")
file <- upload(system.file("CITATION"))
res <- x$post(path = "post", body = list(y = file))
options(warn=2)
#> res <- x$post(path = "post", body = list(y = file))
#> Error in charToRaw(enc2utf8(val)) :
#>   (converted from warning) argument should be a character vector of length 1
#> all but the first element will be ignored

traceback()
#> 8: doWithOneRestart(return(expr), restart)
#> 7: withOneRestart(expr, restarts[[1L]])
#> 6: withRestarts({
#>        .Internal(.signalCondition(simpleWarning(msg, call), msg,
#>     ...
#> 5: .signalSimpleWarning("argument should be a character vector of length 1\nall but the first element will be ignored",
#>        base::quote(charToRaw(enc2utf8(val))))
#> 4: charToRaw(enc2utf8(val))
#> 3: curl::handle_setform(opts$url$handle, .list = opts$fields)
#> 2: private$make_request(rr)
#> 1: x$post(path = "post", body = list(y = file))
```

**Comment by jeroen** [comment]
I think your bug is here:

https://github.com/ropensci/crul/blob/12b11e6ad8a0f2b00d79e934e228bd53dcafa58e/R/body.R#L86

Just don't `as.character()` on `form_file` objects, then you don't need `as.character.form_file`

**Comment by sckott** [comment]
thanks, looks promising

**Comment by sckott** [comment]
@IndrajeetPatil @dpprdan @aoles can you reinstall from master and try again, should be gone now

**Comment by aoles** [comment]
I can confirm that the warning is now gone. Thanks a lot @sckott for your prompt fix!
