### ISSUE TITLE
Is it possible to fire individual async requests?

### ISSUE THREAD

**Issue by TheOnlyArtz** [ropensci/crul#118]
I've encountered an issue, I don't want to fire multiple async requests at once, but a "burst" of individual async requests, let's say I'm using 
```r
library(crul)
req1 <- HttpRequest$new(
  url = "https://httpbin.org/get?a=5",
  opts = list(
    verbose = TRUE
  )
)
req1$get()


req2 <- HttpRequest$new(
  url = "https://httpbin.org/post?a=5&b=6"
)
req2$post(body = list(a = 5))


(res2 <- AsyncVaried$new(req1))
(res <- AsyncVaried$new(req2))

res$request()
res$parse()
res2$request()
res2$parse()
```
this code will not really fire things asynchronously.. how can I fire individual async requests?

**Comment by sckott** [comment]
thanks for the issue. But please clarify what you mean. For example, this is unclear

> this code will not really fire things asynchronously.

how so? 

What does "fire individual async requests" mean?

**Comment by TheOnlyArtz** [comment]
> thanks for the issue. But please clarify what you mean. For example, this is unclear
> 
> > this code will not really fire things asynchronously.
> 
> how so?
> 
> What does "fire individual async requests" mean?

Thanks for the reply, what I mean is, when I use the code I wrote above it seems like it doesn't fire asynchronously, like. speed-wise firing those 2 in the same function call would be much faster, that's how I indicated if it ran async or not, maybe I'm wrong tho

**Comment by sckott** [comment]
I see the problem, you need to do this instead:

```r
AsyncVaried$new(req1, req2)
```

**Comment by sckott** [comment]
i assume this is sorted out, if not we can reopen and continue discussion
