### ISSUE TITLE
why does ok() use head()?

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#123]
``` r
url <- "http://animalnexus.ca"
crul::HttpClient$new(url)$get()$status_code
#> [1] 200
crul::HttpClient$new(url)$head()$status_code
#> [1] 404
```

<sup>Created on 2019-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maelle** [comment]
https://stackoverflow.com/questions/43437667/head-and-get-http-request-return-different-status-code-for-the-same-url

**Comment by maelle** [comment]
| GET_status| HEAD_status|url                                                                                                                                                            |
|----------:|-----------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        200|         404|http://animalnexus.ca                                                                                                                                          |
|         NA|          NA|http://chelsa-climate.org                                                                                                                                      |
|        403|         403|http://lab.brembs.net                                                                                                                                          |
|        200|         200|http://lsi.ubc.ca                                                                                                                                              |
|        200|          NA|http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=11&f=G&l=50&co1=AND&d=PTXT&s1=dog&OS=dog&RS=dog |
|        200|         404|http://seer.r-pkg.org:9200/cran-devel/package/_search?q=%220000-0003-1444-9135%22                                                                              |
|        403|         403|http://steffilazerte.ca                                                                                                                                        |
|        200|         405|http://www.amazon.co.uk                                                                                                                                        |
|        200|         403|http://www.bmj.com/content/357/bmj.j1456                                                                                                                       |
|         NA|          NA|http://www.gadm.org                                                                                                                                            |
|         NA|          NA|http://www.gadm.org                                                                                                                                            |
|        200|         200|http://www.sk-spell.sk.cx/tesseract-ocr-parameters-in-302-version                                                                                              |
|        200|         405|http://www.theregister.co.uk/2011/01/11/transport_for_london_foi                                                                                               |
|        200|         404|https://api.tradestatistics.io                                                                                                                                 |
|        200|         404|https://api.tradestatistics.io/countries                                                                                                                       |
|        200|         405|https://ci.appveyor.com/api/projects/status/4ypc9xnmqt70j94e?svg=true&branch=master                                                                            |
|        200|         405|https://codecov.io/github/ropensci/drake?branch=master                                                                                                         |
|        404|         404|https://cran.r-project.org/bin/linux/debian/jessie-cran3/Release                                                                                               |
|        200|         405|https://deepmind.com                                                                                                                                           |
|         NA|          NA|https://doi.org/10.1080/10635150802158688                                                                                                                      |
|         NA|          NA|https://doi.org/10.1093/aob/mcw118                                                                                                                             |
|         NA|          NA|https://doi.org/10.1093/chemse/bjq042                                                                                                                          |
|        200|         403|https://doi.org/10.1136/bmj.b4469                                                                                                                              |
|        200|         404|https://doi.org/10.2305/IUCN.UK.2014-1.RLTS.T60344A45833138.en                                                                                                 |
|        403|         403|https://doi.org/10.2307/25148773                                                                                                                               |
|        403|         403|https://doi.org/10.2307/25148796                                                                                                                               |
|        200|         405|https://en.vmm.be                                                                                                                                              |
|        200|         405|https://en.vmm.be                                                                                                                                              |
|        200|         404|https://gallery.shinyapps.io/LDAelife                                                                                                                          |
|         NA|          NA|https://hofmann.public.iastate.edu                                                                                                                             |
|         NA|          NA|https://inghaminstitute.org.au                                                                                                                                 |
|        200|         200|https://jeroen.shinyapps.io/shinymagick                                                                                                                        |
|        200|         404|https://jqplay.org                                                                                                                                             |
|        200|         200|https://mahshaaban.shinyapps.io/colocr_app2                                                                                                                    |
|        200|         405|https://mybinder.org                                                                                                                                           |
|        200|         200|https://sheffield-university.shinyapps.io/ReproHack_CCMcr                                                                                                      |
|        200|         200|https://sheffield-university.shinyapps.io/ReproHack_CCMcr                                                                                                      |
|        200|         200|https://theintercept.com/staff/glenn-greenwald                                                                                                                 |
|         NA|          NA|https://www.eugdpr.org                                                                                                                                         |
|        200|         405|https://www.instagram.com/juliana.wildlife                                                                                                                     |
|        403|         403|https://www.jstor.org/dfr                                                                                                                                      |
|        999|         999|https://www.linkedin.com/in/jonasgeschke                                                                                                                       |
|        200|         200|https://www.ncbi.nlm.nih.gov/books/NBK279671                                                                                                                   |
|         NA|         200|https://www.ncbi.nlm.nih.gov/books/NBK279671                                                                                                                   |
|        200|         200|https://www.ncbi.nlm.nih.gov/genbank                                                                                                                           |
|        200|         200|https://www.ncbi.nlm.nih.gov/genbank                                                                                                                           |
|        200|         200|https://www.ncbi.nlm.nih.gov/genbank                                                                                                                           |
|        200|         200|https://www.ncbi.nlm.nih.gov/pubmed/28606699                                                                                                                   |
|        200|         200|https://www.ncbi.nlm.nih.gov/Sequin/acc.html                                                                                                                   |
|         NA|         200|https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1445963                                                                                  |
|        200|         200|https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9504                                                                                     |
|        502|         502|https://www.reddit.com/r/dataisbeautiful                                                                                                                       |
|        200|         405|https://www.thinkwithgoogle.com/data-gallery/detail/google-app-voice-search                                                                                    |

**Comment by sckott** [comment]
http://www.gadm.org/ is a weird one. even `followlocation=TRUE` option doesn't redirect to the new url at https://gadm.org/

**Comment by sckott** [comment]
@maelle ok, added `verb` param to ok, `remotes::install_github("ropensci/crul@ok-http-verbs")` - try it out if you get a chance,
