### ISSUE TITLE
Add grouping to reference page?

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#131]
It might even be good to use `@family` (roxygen2) and `has_concept()` for that. E.g. all HTTP client classes could be in a family (so from the man page for Async I'd see AsyncVaried but also httpClient).

Example of a pkgdown website organized with this strategy: https://github.com/ropensci/stplanr/blob/master/_pkgdown.yml

**Comment by sckott** [comment]
yes, will do. 

good idea about family tag.
