### ISSUE TITLE
Add an article "How to choose a client?"

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#133]
Maybe with even a comparative table. Maybe a new article maybe a section of https://docs.ropensci.org/crul/articles/how-to-use-crul.html

Things that could be mentioned:

* With Async you can make several requests in parallel. With AsyncVaried too, and you need AsyncVaried when blabla varies.

* No retrying with Async.

* When to use paginator. Does Paginator do async?

For each client maybe there could be an example of a package using the class?

**Comment by maelle** [comment]
note from a convo. Paginator for the cases when you don't know the total number of results.

**Comment by sckott** [comment]
Thanks @maelle 

maybe its best as a part of the how to use crul vignette since maybe users won't know what a "client" is, but in context of the vignette it would be an easier path for them

all of those topics sound good.
