### ISSUE TITLE
new client to handle use case: async w/ rate limits

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#139]
user says that ratelimitr doesn't work with async requests (does w/ regular sync requests though) - wants to do async requests w/ API that has 2 rate limits: 1/sec & 100/hr

duckduckgoing around a bit, seems theres some discussion of a queueing approach, and firing off sets of async requests every X time step. 

perhaps:

```r
# bucket_size=number of requests sent in one async request
# sleep: sleep time between each bucket of requests
AsyncQueue$new(
  urls = list_of_some_urls,
  bucket_size = 10, sleep = 10
)
# OR
AsyncQueue$new(
  urls = list_of_some_urls,
  bucket_size = 10, rate_per_sec = 1
)
# OR
AsyncQueue$new(
  urls = list_of_some_urls,
  bucket_size = 10, rate_per_hr = 100
)
# OR just rate, and it figures out bucket size, seems easiest for user 
AsyncQueue$new(
  urls = list_of_some_urls,
  rate_per_hr = 100
)
```

**Comment by sckott** [comment]
@johnbaums can you restart R, install `remotes::install_github("ropensci/crul@async-queue")` , and see `?AsyncQueue`  - sleeping between sets of request works, but not requests per second or hr yet, not quite sure how to do those yet

**Comment by johnbaums** [comment]
Awesome, thanks @sckott. Sounds like great progress - really appreciate it.

**Comment by sckott** [comment]
@johnbaums let me know if you try it and have any feedback
