### ISSUE TITLE
about choosing a client

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#143]
Nice table! It'll be even better when the combos retry+pagination and retry+async exist :stuck_out_tongue_winking_eye: 

The name of packages using the clients is super useful, how about adding permalinks to the relevant code lines on GitHub? So for each package, linking both its homepage, and adding GitHub permalinks. These will probably get out-of-date though, so maybe just linking the homepage is a better idea?

**Comment by sckott** [comment]
Agree I don't think we should link to the code lines as those will surely change. What homepage do you mean? https://github.com/ropensci/crul/ ? or a different one?

**Comment by maelle** [comment]
The homepage of each package e.g. duckduckr.

**Comment by sckott** [comment]
ohhh, i see, ok
