### ISSUE TITLE
Add support for pagination for Async calls

### ISSUE THREAD

**Issue by moldach** [ropensci/crul#160]
Hoping you can help me try to troubleshoot an error I'm running into.

When I make a standard `curl` request for the API from the command line I see that there are _many pages_ for `TNF-alpha`: ` curl -X GET "https://api.targetsafety.info/api/target/alerts/param?uniprotid=P01375&page=1&token=[MyPrivateKey]" > tnf_alpha.json`

We see that the created `.json` file shows that there are **17 pages** (and that this request is only showing page 1/17):

```
{
  "page": 1,
  "numberPages": 17,
  "targets": [
    {
      "target_id": 348,
      "target_name": "TNF-alpha",
      "actions": [
        {
          "action_id": 15,
          "action_name": "Inhibitors",
          "alerts": [
            {
              "affected_system_id": 10005329,
              "affected_system": "blood and lymphatic system disorders",
              "adverse_event_id": 10043554,
              "adverse_event": "thrombocytopenia",
              "ref_id": 95580,
...
```

Since I'm making 100s thousands of API calls with `AsyncQueue()` each of them _will have different number of pages_. 

How is it possible to crawl each of these pages using `AsyncQueue()`? 

Currently only the `1st` of `x` pages are being shown (_note: dropping `&page=1` from the url results in a broken API call - the _exact_ page number _must_ be specified).

However, currently I see the following [note in the documents about **Paginator**](https://docs.ropensci.org/crul/articles/choosing-a-client.html):

> Paginator is a class for automating pagination. It requires an instance of HttpClient as it’s first parameter. It does not handle asynchronous requests at this time, but may in the future. Paginator may be the right class to use when you don’t know the total number of results. Beware however, that if there are A LOT of results (and a lot depends on your internet speed and the server response time) the requests may take a long time to finish - just plan wisely to fit your needs.

If this isn't supported yet it would be greatly welcomed in the near future 😁

**Comment by sckott** [comment]
Thanks for the bump, will try to get this done

**Comment by sckott** [comment]
I think this would only work for async when we can construct URLs ahead of time because the whole point of async requests is to send off a bunch of requests at the same time. Thus, it can't work if you have to do request A to get the information to do request B. Should work if e..g, you know you want 1000 results, and you know the pagination query param names

**Comment by moldach** [comment]
Yeah it looks like it would need to be a two-step process than since we don't know the range of values to give for `page=<n>` where _n_ is _unknown_:

<div class="pull-left" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; float: left !important; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="box-sizing: border-box; font-size: 20px; margin: 0px 0px 20px; font-family: &quot;Source Sans Pro Bold&quot;, sans-serif; font-weight: 600; line-height: 26px; color: inherit; padding: 0px;">Alerts Information Uniprot - Get target alerts by uniprotid</h1></div><div class="pull-right" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; float: right !important; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="btn-group" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; position: relative; display: inline-block; vertical-align: middle;"><button class="version btn btn-default dropdown-toggle" data-toggle="dropdown" style="box-sizing: border-box; color: rgb(51, 51, 51); font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: 1.42857; font-family: inherit; margin: 0px; overflow: visible; text-transform: none; appearance: button; cursor: pointer; display: inline-block; text-align: center; white-space: nowrap; vertical-align: middle; touch-action: manipulation; background-image: none; border: 1px solid rgb(204, 204, 204); padding: 6px 12px; border-radius: 4px; user-select: none; background-color: rgb(255, 255, 255); position: relative; float: left;"><strong style="box-sizing: border-box; font-weight: 700;">1.0.0</strong> <span class="caret" style="box-sizing: border-box; display: inline-block; width: 0px; height: 0px; margin-left: 0px; vertical-align: middle; border-top: 4px dashed; border-right: 4px solid transparent; border-left: 4px solid transparent;"></span></button></div></div><div class="clearfix" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><span class="type type__get" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 600; font-size: 15px; display: inline-block; margin: 0px 0px 5px; padding: 4px 5px; border-radius: 6px; text-transform: uppercase; background-color: green; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">GET</span><span style="color: rgb(51, 51, 51); font-family: &quot;Source Sans Pro&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><pre class="prettyprint language-html prettyprinted" data-type="get" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 1em; margin: 0px 0px 20px; line-height: 1.42857; color: rgb(255, 255, 255); word-break: break-all; overflow-wrap: break-word; background-color: rgb(0, 0, 0); border: 1px solid rgb(204, 204, 204); border-radius: 8px; position: relative; width: 780px; white-space: pre-wrap; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box; font-family: &quot;Source Code Pro&quot;, monospace; font-size: 14px; padding: 0px; color: inherit; background-color: transparent; border-radius: 0px; white-space: pre; display: block; font-style: normal; font-weight: 400; overflow-wrap: normal;"><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">https://api.targetsafety.info/api/target/alerts/param?</span></code></pre><h2 style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 600; line-height: 24px; color: rgb(51, 51, 51); margin: 0px 0px 10px; font-size: 18px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Parameter</h2>

Field | Type | Description
-- | -- | --
uniprotid | String | [required] Uniprot ID
page | Number | [required] Page number
token | String | [required] Token
adverse_event_idoptional | Number | [optional] Adverse Event ID
ref_source_typeoptional | String | [optional] Reference source type
alert_typeoptional | String | [optional] Alert Type
alert_phaseoptional | String | [optional] Alert Phase
alert_level_evidenceoptional | String | [optional] Level of evidence
alert_onoff_targetoptional | String | [optional] On/Off target
alert_severityoptional | String | [optional] Alert Severity
alert_speciesoptional | String | [optional] Alert Species
alert_date_fromoptional | String | [optional] Date from
alert_date_tooptional | String | [optional] Date to
order_by_dateoptional | String | [optional] Order by dateOnly one ordering is possible
order_by_advoptional | String | [optional] Order by adverse eventOnly one ordering is possible

<h2 style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 600; line-height: 24px; color: rgb(51, 51, 51); margin: 0px 0px 10px; font-size: 18px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Success 200</h2>

Field | Type | Description
-- | -- | --
page | Number | Page
numberPages | Number | Number pages
target_id | Number | Target ID
target_name | String | Target name
action_id | Number | Action ID
action_name | String | Action name
alerts | Object[] | Alerts
affected_system_id | Number | Affected system ID
affected_system | String | Affected system
adverse_event_id | Number | Adverse event ID
adverse_event | String | Adverse event
ref_id | Number | Reference ID
ref_source_type | String | Reference source type
ref_title | String | Reference title
ref_citation | String | Reference citation
ref_pubmed_id | Number | PubMed ID
ref_link | String | Reference link
ref_date | String | Reference date
alert_detail_id | Number | Alert detail ID
alert_title | String | Alert title
alert_date | String | Alert date
alert_genetic_study_variant | String | Alert genetic study variant
alert_type | String | Alert type
alert_phase | String | Alert phase
alert_onoff_target | String | On/Off target
alert_level_evidence | String | Level of evidence
alert_severity | String | Alert severity
alert_species | String | Alert species
drugs | Object | Drugs related
drug_id | Number | Drug ID
drug_name | String | Drug name

<ul class="nav nav-tabs nav-tabs-examples" style="box-sizing: border-box; margin: 0px; padding-left: 0px; list-style: none; border-bottom: 1px solid rgb(221, 221, 221); color: rgb(51, 51, 51); font-family: &quot;Source Sans Pro&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="active" style="box-sizing: border-box; position: relative; display: block; float: left; margin-bottom: -1px;"><a href="https://api.targetsafety.info/apidoc/#success-examples-TARGETS-Alerts_Information_Uniprot-1_0_0-0" style="box-sizing: border-box; background-color: rgb(255, 255, 255); color: rgb(85, 85, 85); text-decoration: none; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; position: relative; display: block; padding: 10px 15px; margin-right: 2px; line-height: 1.42857; border-width: 1px; border-style: solid; border-color: rgb(221, 221, 221) rgb(221, 221, 221) transparent; border-image: initial; border-radius: 4px 4px 0px 0px; cursor: default;">Success Response</a></li></ul><div class="tab-content" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="tab-pane active" id="success-examples-TARGETS-Alerts_Information_Uniprot-1_0_0-0" style="box-sizing: border-box; font-family: &quot;Source Sans Pro&quot;, sans-serif; font-weight: 400; font-size: 16px; display: block;"><pre class="prettyprint language-json prettyprinted" data-type="json" style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 1em; margin: 1em auto; line-height: 1.42857; color: rgb(255, 255, 255); word-break: break-all; overflow-wrap: break-word; background-color: rgb(0, 0, 0); border: 1px solid rgb(204, 204, 204); border-radius: 8px; position: relative; width: 780px; white-space: pre-wrap;"><code style="box-sizing: border-box; font-family: &quot;Source Code Pro&quot;, monospace; font-size: 14px; padding: 0px; color: inherit; background-color: transparent; border-radius: 0px; white-space: pre; display: block; font-style: normal; font-weight: 400; overflow-wrap: normal;"><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">{</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"page"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">1</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"numberPages"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">11</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"targets"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">[</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
        </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">{</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"target_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">158</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"target_name"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"SGLT2"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"actions"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">[</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">{</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"action_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">2</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"action_name"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Activators"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                    </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alerts"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">[</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                        </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">{</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"affected_system_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">10015919</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"affected_system"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"eye disorders"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"adverse_event_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">10015916</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"adverse_event"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"eye disorder"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">62872</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_source_type"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Journal"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_title"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Leveraging Human Genetics to Identify Safety Signals Prior to Drug Marketing Approval and Clinical Use"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_citation"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Drug Saf 2020 Feb 28"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_pubmed_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"32112228"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_link"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="kwd" style="box-sizing: border-box; color: rgb(226, 137, 100);">null</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"ref_date"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"2020-02-28"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_detail_id"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="lit" style="box-sizing: border-box; color: rgb(51, 135, 204);">662867</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_title"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Phenome-wide association study identifying human gene mutations that could be used for in silico prediction of potential adverse drug effects. Results revealed 8 positive associations correlating gene mutation phenotypes with known safety signals from drugs targeting the protein. These associations were PCSK9 (spina bifida), TNF-alpha (cellulitis and leg abscess), PPARgamma (obesity), estrogen receptor-alpha (hemorrhages), ACE (congenital urinary anomalies), phospholipase A2 (primary hypercoagulable state), GluN2B (symbolic dysfunction) and GluN2A (paroxysmal tachycardia, pulmonary heart disease and sleep disorders). Other safety issues are listed."</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_date"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"2020-03-11"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_genetic_study_variant"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"gain-of-function mutation"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_type"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Class Alert"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_phase"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Target Discovery"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_onoff_target"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"On-Target"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_level_evidence"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"Suspected"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_severity"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"no"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"alert_species"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"human"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">,</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                            </span><span class="str" style="box-sizing: border-box; color: rgb(101, 176, 66);">"drugs"</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">:</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);"> </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">[]</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                        </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">}</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                    </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">]</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
                </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">}</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
            </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">]</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
        </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">}</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
    </span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">]</span><span class="pln" style="box-sizing: border-box; color: rgb(255, 255, 255);">
</span><span class="pun" style="box-sizing: border-box; color: rgb(255, 255, 255);">}</span></code></pre></div></div>


Only upon a successful API call (**Success 200**) would we get _n_ from `numberPages`.
So with a bit more effort we could grep `numberPages` from each successful API call and then construct these URLs ahead of time.

Closing this issue since I asked them to provide us with a bulk data download instead... 💁🏼
