### ISSUE TITLE
Async$get fails with non default disc param

### ISSUE THREAD

**Issue by shakraz** [ropensci/crul#165]
Hello there
Running out of memory processing 100K requests, so using **disc** param should help, 
```
cc <- Async$new(urls = c('https://httpbin.org/'))
res <- cc$get(disk=tempfile())
```
but i'm getting the error:
**Error in initialize(...) : object 'reqs' not found**
Didn't find anything relevant in SO, thank you for any help or suggestion

**Comment by sckott** [comment]
thanks, i thjink i have the fix on a different branch

**Comment by shakraz** [comment]
hey, thank you for quick reply!
reinstalled the package from **async-fix-disk-ifelse** branch, but getting the following:
**Error in private$gen_interface(self$urls, "get", path, query, disk = disk,  : 
  length(x) == length(disk) is not TRUE**

**Comment by sckott** [comment]
@shakraz i see you deleted your comment about a length mismatch. the number of urls you use must be the same length as the number of file paths given to `disk`. i just made the error message better for that.

**Comment by sckott** [comment]
```r
library(crul)
cc <- Async$new(urls = c('https://httpbin.org/'))
res <- cc$get(disk=c(tempfile(), tempfile()))
#> Error in private$gen_interface(self$urls, "get", path, query, disk = disk,  :
#>   urls must be same length as disk
```
