### ISSUE TITLE
Set custom user agent and proxy

### ISSUE THREAD

**Issue by artemklevtsov** [ropensci/crul#22]
Hi.

Many thanks for the nice package.

How can I set a some custom options for the requests? For example user agent and proxy server.

**Comment by artemklevtsov** [comment]
Seems I found solution for the user agent.

```r
client1 <- HttpClient$new(url = "https://google.com")
client2 <- HttpClient$new(url = "https://google.com", opts = list(useragent = "my-header"))
client1$get()$request_headers
#> $useragent
# > [1] "libcurl/7.52.1 r-curl/2.3 crul/0.2.0"
client2$get()$request_headers
#> $useragent
# > [1] "my-header"
```

**Comment by sckott** [comment]
that's right on user-agent

will look into proxy

**Comment by sckott** [comment]
@artemklevtsov  reinstall  - see `?proxies` after reinstall, let me know if it works for you

**Comment by artemklevtsov** [comment]
3630d8321113a4a8871c72d5e1f911867159c104 looks good. Thank you for the quick resolution.

**Comment by sckott** [comment]
thx, did you try it ?

**Comment by artemklevtsov** [comment]
Works fine:

```r
devtools::install_github("ropensci/crul")
library(crul)
cl1 <- HttpClient$new(url = "http://ip.tyk.nu")
cl1$get()$parse("UTF-8")
#> [1] "46.*.*.*"
proxies <- c(proxy("103.28.225.180:8080"))
cl2 <- HttpClient$new(url = "http://ip.tyk.nu", proxies = proxies)
cl2$get()$parse("UTF-8")
#> [1] "103.28.225.180"
```

I think notes about user agent should be added to the man.

**Comment by sckott** [comment]
Great, still need to figure way to support multiple proxies
