### ISSUE TITLE
Async response objects sometimes point to wrong requests objects

### ISSUE THREAD

**Issue by dirkschumacher** [ropensci/crul#41]
When making async requests, responses come back unordered which is fine. However it seems like the associated request objects accessible via `$request` are always ordered in the original way.

This means that in case responses do not come back in the same order as the original requests, the associated request of the respective response might be wrong.

Here is a minimal example that sometimes works and sometimes not:
```R
library(crul)
(cc <- Async$new(
  urls = c(
    'https://httpbin.org/get?a=5',
    'https://httpbin.org/get?a=5&b=6',
    'https://httpbin.org/ip'
  )
))
(res <- cc$get())

# the following line prints all urls of the original request object
print(sapply(res, function(x) x$request$url))
# this prints all response urls
print(sapply(res, function(x) x$url))
# those two values should be equal I assume
```

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin16.5.0 (64-bit)
Running under: macOS Sierra 10.12.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] crul_0.3.6

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  R6_2.2.1        tools_3.4.0     withr_1.0.2    
 [5] rstudioapi_0.6  curl_2.6        memoise_1.1.0   Rcpp_0.12.11   
 [9] urltools_1.6.0  triebeard_0.3.0 digest_0.6.12   devtools_1.13.1
```

**Comment by sckott** [comment]
thanks! looking at it

**Comment by sckott** [comment]
@dirkschumacher made a change, reinstall and try again

**Comment by sckott** [comment]
cc @maelle cause i think you're using async stuff as well

**Comment by dirkschumacher** [comment]
Looks good. Seems like the responses now always come back in the order of the requests?

**Comment by sckott** [comment]
as far as i can tell, yes - added tests to check that it does - and those pass - 

but do let me know if you find a case in which the ordering isn't correct

**Comment by dirkschumacher** [comment]
All good I think :)

**Comment by sckott** [comment]
great, will send a new version to cran soon
