### ISSUE TITLE
sticker idea

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#42]
https://twitter.com/hadleywickham/status/875554298729574400

http://krull.wikia.com/wiki/Glaive

**Comment by sckott** [comment]
in commit a53055da13688e29cf8d34cd2dc09acb2548db98

from: https://www.reddit.com/r/polymerclay/comments/anmulw/the_glaive_from_the_1982_fantasy_movie_krull/
image link: https://i.redd.it/3d40swikive21.jpg 
code:

```r
library(hexSticker)
path <- "~/Downloads/glaive-transparent-silver.png"
sticker(path, package="",
  p_x=1, p_y=1.1, p_size=18, p_family="serif", p_color="#E3DCFF",
  s_x=1, s_y=1.1, s_width=0.9, 
  h_color="#E3DCFF", h_fill="#17181F", filename="crul.png",
  url="crul", u_size=5, u_x = 1.46, u_y = 0.43, u_angle=33, u_color="#E3DCFF")
```

**Comment by sckott** [comment]
https://github.com/ropensci/crul/blob/master/man/figures/logo.png

**Comment by sckott** [comment]
any thoughts @maelle ?

**Comment by maelle** [comment]
Cool! An explanation of the logo meaning could be added somewhere in the package docs :slightly_smiling_face:

**Comment by sckott** [comment]
Good idea
