### ISSUE TITLE
get/set cookie?

### ISSUE THREAD

**Issue by happyshows** [ropensci/crul#44]
Hi,

I have a use case where I need to set up cookie value when running GET/POST method (for a tmp authentication purpose). Is there a way to do so in this package?

**Comment by sckott** [comment]
thanks for the issue @happyshows 

at the moment there's nothing built in to help with cookies. 

you can set them manually like 

```r
x <- HttpClient$new(
  url = "https://httpbin.org",
  opts = list(cookie = "c=1;f=5")
)

# set cookies
res <- x$get("cookies")
jsonlite::fromJSON(res$parse("UTF-8"))
```

but they aren't yet persisted across requests - working on that

working on some docs for this

**Comment by sckott** [comment]
DOAJ sets cookies - good eg to work with

**Comment by sckott** [comment]
@happyshows can you reinstall `devtools::install_github("ropensci/crul")` and try again? let me know if cookies work for you for your use case

**Comment by sckott** [comment]
i think we're good here
