### ISSUE TITLE
[Question] Async requests to disk

### ISSUE THREAD

**Issue by artemklevtsov** [ropensci/crul#46]
Hi,

How can I use the async feature with `disk` or `stream` params for the `GET` method?

~~
Regards

**Comment by sckott** [comment]
thanks @artemklevtsov 

looking into it ...

**Comment by sckott** [comment]
not sure yet if disk or stream is possible when doing async with `curl` - checking on that

**Comment by sckott** [comment]
@artemklevtsov heard back from Jeroen. it's not currently possible to do write to disk or do streaming while doing async - Sorry 😢

**Comment by artemklevtsov** [comment]
Ok, `parallel::mccollect` still works :)

**Comment by sckott** [comment]
@artemklevtsov good to know. can you show an example of how you use that with `crul`?

**Comment by sckott** [comment]
@artemklevtsov looks like we can now do this https://github.com/jeroen/curl/issues/118 - will work on this soon

**Comment by artemklevtsov** [comment]
Good news. Now I use `curl_ferch_multi` with the `done` callback function. It look like this:

```r
success <- function(resposne) {
    if (resposne$status_code >= 400L) {
        flog.warn("Can't retrieve URL with status code %s: %s", resposne$status_code, resposne$url)
        return()
    }
    dest <- file.path(outdir, basename(resposne$url))
    flog.debug("Write content to file: %s", dest)
    writeBin(resposne$content, dest)
}
```

**Comment by sckott** [comment]
actually, have to yank this stuff out as relies on dev `curl` that isn't on cran yet, and need to get new version of this up soon for other pkgs that depend on it

**Comment by sckott** [comment]
is on branch `async-disk-stream` for now, install like `devtools::install_github("ropensci/crul@async-disk-stream")` to use it. master will soon not have this stuff

**Comment by sckott** [comment]
@artemklevtsov finally getting back to this, changes are on branch https://github.com/ropensci/crul/tree/async-disk-stream - to merge into master soon. hoping to get new version to cran in the next few days
