### ISSUE TITLE
async - parallelization use cases

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#47]
via https://stackoverflow.com/questions/45573770/how-do-i-perform-parallel-asynchronous-post-api-calls-in-r/45575252

**Comment by sckott** [comment]
From the SO thread, seems like there's 2 issues:

- curl handles when creating lots of requests in parallel 
- feature request to support parallel usage in one way or another

**Comment by rohan-gt** [comment]
I think the two major features that can be added to existing crul functions are:
1. Fast parallel creation of requests and adding them to a request pool
2. Parallel asynchronous execution of requests from from the request pool

**Comment by sckott** [comment]
thanks @rohan-gt 

For the handle issue, we need a smaller reproducible example (smaller than the 150K requests you mentioned in the SO thread).  Can you give one here so we can reproduce and try to find solution?

**Comment by sckott** [comment]
note that @jeroen (`curl` pkg maintainer) suggests to avoid parallel and just use the async feature for all the requests - there's no known max number of requests where problems should occur - though if they do let us know. 

Note also that with async, you can't write to disk or stream - you have to collect response and then parse it/etc in R, then can write to disk if you like

**Comment by sckott** [comment]
thoughts on your list

> 1. Parallel creation of requests (ideally from a list of urls, JSON bodies etc.) and adding them to a request pool 

can look into this - though that can easily be done outside of this pkg 

> 2. Parallel asynchronous execution of requests from from the request pool

this is unlikely to happen - see also comment above - did you try just sending all requests into the same async call?  if that errors, let us know and we can see if there's a solution

> 3. An optional parameter to set a delay between a set number of requests so as to prevent throttling of a webpage/API

This is likely outside scope of this package. You can do this yourself. If you know e.g., 1000 requests allowed per minute - then could chunk requests into sets of 1000 each, do async requests on each chunk with a `Sys.sleep(time)` in between each
