### ISSUE TITLE
vignettes names

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#64]
I was puzzled by the existence of a crul intro and of "how to use crul" because I didn't know on which to click first. Should you number them or maybe merge them?

**Comment by sckott** [comment]
good question, we should have a look at them and see about merging/renaming, will have a look

**Comment by maelle** [comment]
I'll definitely read the vignettes again soon so will revisit this issue with suggestions.

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
perhaps 'Using crul in functions/packages'
