### ISSUE TITLE
Unable to pass a list of requests to AsyncVaried

### ISSUE THREAD

**Issue by parts-rescue** [ropensci/crul#69]
I am attempting to do asynchronous API calls using crul library.  

The following gives me a list of 2 http requests : 

```
siteId[1]=80
siteId[2]=81
request<-vector(mode = "list")
base <- "https://example.com/api/"
api <- "TestAPI/"
for(i in 1:2)){
    endpoint <- paste0("GetData/Json?SiteId=",siteId[i])
    url=paste0(base,api,service,endpoint)
    next_request <-HttpRequest$new(url = url, auth=auth(usr,auth$password,auth="basic"))$get()
    request <- c(request,next_request)
  }
```

Per the crul documentation this works as expected:
` api_data <- AsyncVaried$new(request[[1]],request[[2]])`

The problem is I am only using a list of 2 as an example.  Normally, I will have a list of SiteIds of varying length and can be up to 300 items long.

So I want to use:
`api_data <- AsyncVaried$new(request)`
But when I try that I get error:   
> Error: all inputs must be of class 'HttpRequest'

I can confirm with certainty that variable 'request' is a list of length two and I know they are both httprequest objects since it works in the first example where each item is listed on it's own.

I am new to R and not a professional developer so there might be a very simply answer but asking the question here rather than stackexchange since it might help to modify the documentation for this kind of example which I assume is more common for async GET requests.

**Comment by sckott** [comment]
thanks for your question @parts-rescue !

have  you seen the `.list` parameter? eg here in the docs  https://github.com/ropensci/crul/blob/master/R/asyncvaried.R#L92-L105

**Comment by parts-rescue** [comment]
I am so sorry.  I should have read the documentation in more detail before posting this question as an issue.  
`api_data <- AsyncVaried$new(.list=request)`
Worked perfect.   Thank you!

**Comment by sckott** [comment]
no worries, glad to see the pkg is useful 😸

**Comment by parts-rescue** [comment]
The package is very useful.   I closed this issue but hoping maybe you can answer one more question.   I use CRUL successfully to make asynchronous calls on my laptop but when I moved the script to my linux server running on a very small VM, I get an error.

I have a list of two requests in api_request.
`api_response <- api_request$request()`

On my laptop, I get the expected responses which I am able to parse.
On my linux server, running the same script, I get:
> Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
>   zero-length inputs cannot be mixed with those of non-zero length

I am guessing the root cause is that there are issues due to the size of the server but I don't know how to resolve.

If this question should be moved elsewhere or to a new issue, feel free to let me know.  Thanks!

**Comment by parts-rescue** [comment]
I solved the "zero-length" problem.   Adding opts = list(verbose = TRUE) to the request helped me see that curl was having problems with an invalid SSL certificate.  

Adding` set_config(config(ssl_verifypeer = 0L)) ` to my script set curl to ignore certificate verification.

**Comment by sckott** [comment]
glad its useful for you! 

You were spot on using verbose curl output to check the curl operations. Nice work sorting it out.
