### ISSUE TITLE
add helper similar to httr::url_ok()?

### ISSUE THREAD

**Issue by maelle** [ropensci/crul#71]

**Comment by sckott** [comment]
the body of the function has a warning and says `please use `identical(status_code(x), 200L)` instead.`

is the main purpose to use in tests? or something else?

**Comment by maelle** [comment]
I think it's quite common to want to "test" an URL e.g. I'd like to suggest to @cboettig to replace the `httr` dependency with `crul` in `codemetar` 👼 and it could be cool to solve https://github.com/ropensci/codemetar/issues/68 with a single crul function? Potentially not as useful as I think though?

**Comment by sckott** [comment]
seems like a good idea ✔️

**Comment by sckott** [comment]
@maelle `ok()` , thoughts?

**Comment by maelle** [comment]
Looks good, thanks a ton! Could you also export a helper giving the status code? Or have the status code as attribute of the output? E.g for codemetar I'd like to message or return the code when it is not 200.

**Comment by sckott** [comment]
what do you mean by a helper? from what?

there's this, but is it not quite what you want?:

```r
HttpClient$new("https://httpbin.org/get")$get()$status_code
#> 200
```

**Comment by maelle** [comment]
Yes I'd wrap this in a single function. But ok is a fine function as it is ☺

**Comment by sckott** [comment]
> wrap this in a single function

what do you mean by _this_?

**Comment by maelle** [comment]
Your code example so that blabla(url) -> http code

**Comment by sckott** [comment]
well, the high level approach with `crul` is to use an `R6` class based workflow, so we create R6 objects, then call methods on those objects, so i probably don't want to start creating accessor methods that duplicate what's already possible by calling a method on the object.

**Comment by maelle** [comment]
Yep this function would only live in utils.R of another package :-)

**Comment by sckott** [comment]
okay, merged in @maelle

**Comment by maelle** [comment]
Thank you 😀
