### ISSUE TITLE
`Async` problem: urls that don't exist error and are dropped 

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#74]
presumably affects `AsyncVaried` as well

**Comment by sckott** [comment]
seems there's a variety of ways this could work on failure/error

- return NULL/NA/etc. 
- tryCatch and return the error message from `curl`

maybe we can have a parameter and a user can pass in a function?

**Comment by sckott** [comment]
@maelle @jeroen 

thoughts on this behavior, does it make sense. `remotes::install_github("ropensci/crul@curl-fail-behavior")`

With the above commit Async/AsyncVaried just capture a failed request that doesn't give a proper HTTP status code e.g., "Could not resolve host" and "Failed to connect to ..." and "Resolving timed out after ..."

--- 

for perspective:

- Ruby's `faraday` https://github.com/lostisland/faraday/wiki/Parallel-requests gives back a response object just as with a non-failed request, but with a `0` status code, but AFAICT they don't give back the error message from curl
- Python's `grequests` https://github.com/kennethreitz/grequests returns `None` when there's a curl error (equivalent of `NULL` in R - so you can't do anything on that response)

**Comment by maelle** [comment]
It makes me think of `purrr::safely` where output is two lists right? One with errors and one with successes.

**Comment by maelle** [comment]
In any case it's useful to have "the error message from curl" as mentioned above.

**Comment by sckott** [comment]
hmm, yeah, but I do like the idea of keeping the order that requests were given the same as order returned

**Comment by maelle** [comment]
Good point.

**Comment by sckott** [comment]
merged in #84
