### ISSUE TITLE
event hooks

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#76]
http://docs.python-requests.org/en/master/user/advanced/#event-hooks

not sure if useful, good idea, and if possible in R yet.

**Comment by sckott** [comment]
Def possible. Requests seems to only modify response and not request.

 Use cases;

- print info during fxn call
- modify parsing of response

**Comment by sckott** [comment]
https://alexwlchan.net/2017/10/requests-hooks/

**Comment by sckott** [comment]
(pinging folks that have opened issues in this repo in case you find this of interest @maelle @artemklevtsov @ben519 @billdenney  - would appreciate any feedback before merging this into master)

Added a new feature on the [hooks branch](https://github.com/ropensci/crul/tree/hooks) install with `remotes::install_github("ropensci/crul@hooks")`

To get an idea of what this does see similar feature for Python's requests http://docs.python-requests.org/en/master/user/advanced/#event-hooks or for httr (where they're called callbacks) https://httr.r-lib.org/reference/get_callback.html

A few quick examples from the docs, see `?hooks`

```r
library(crul)

# hooks on the request
fun_req <- function(request) {
  cat("Requesting: ", request$url$url, sep = "\n")
}
x <- HttpClient$new(url = "https://httpbin.org",
  hooks = list(request = fun_req))
r1 <- x$get('get')
#> Requesting:
#> https://httpbin.org/get

# hooks on the response
fun_resp <- function(response) {
   cat(paste0("status_code: ", response$status_code), sep = "\n")
}
x <- HttpClient$new(url = "https://httpbin.org",
   hooks = list(response = fun_resp))
r1 <- x$get('get')
#> status_code: 200
```

**Comment by maelle** [comment]
Cool! I've played with the code above a bit, and when modifying it I saw one gets a warning now if hooks is a named list of a length more than 1, probably an easy fix.

``` r
library(crul)

# hooks on the request
fun_req <- function(request) {
  cat("Requesting: ", request$url$url, sep = "\n")
  beepr::beep()
}
x <- HttpClient$new(url = "https://httpbin.org",
                    hooks = list(request = fun_req))
r1 <- x$get('get')
#> Requesting: 
#> https://httpbin.org/get

# hooks on the response
fun_resp <- function(response) {
  cat(paste0("status_code: ", response$status_code), sep = "\n")
}
x <- HttpClient$new(url = "https://httpbin.org",
                    hooks = list(response = fun_resp, 
                                 request = fun_req))
#> Warning in if (!has_name(hooks)) stop("'hooks' must be a named list"): the
#> condition has length > 1 and only the first element will be used
r1 <- x$get('get')
#> Requesting: 
#> https://httpbin.org/get
#> status_code: 200
```

<sup>Created on 2019-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

(The use of `beepr` improves the experience a lot :joy_cat: )

**Comment by maelle** [comment]
In the docs "Trigger functions to run on requests and/or responses" could be "Trigger functions to run on/after requests and/or responses", right? A "Details" section with more, well, details and ideas of use cases would be great.

**Comment by maelle** [comment]
Idea for an example: make the `beepr::beep()` depend on the status code.

```r
library(crul)

# hooks on the response
fun_resp <- function(response) {
  cat(paste0("status_code: ", response$status_code), sep = "\n")
  if(response$status_code == 200){
    beepr::beep(3)
  } else {
    beepr::beep(9)
  }
}
x <- HttpClient$new(url = "https://httpbin.org",
                    hooks = list(response = fun_resp))
r1 <- x$get('get')
r2 <- x$get('get2')
```

**Comment by sckott** [comment]
thanks for the feedback! 

i like the beepr idea 😄

**Comment by sckott** [comment]
fixes made, no more warning
