### ISSUE TITLE
Add async support

### ISSUE THREAD

**Issue by sckott** [ropensci/crul#8]

**Comment by sckott** [comment]
started draft in branch async https://github.com/ropensci/crul/tree/async

**Comment by sckott** [comment]
@artemklevtsov let me know what you think of the async interfaces on this branch https://github.com/ropensci/crul/tree/async

**Comment by artemklevtsov** [comment]
I think it's very interesting and useful. Also we need a some tests before merge with master.

**Comment by sckott** [comment]
> 1) flowcharts of async vs synchronous like this one http://www.read.cs.ucla.edu/111/_media/notes/pipelining.jpg maybe you could add something similar to the README/vignette once you add async? 2) being nice with the data provider. 3) seealso for each async fxn

**Comment by artemklevtsov** [comment]
We can use https://httpbin.org/delay/1 to test async client.

**Comment by sckott** [comment]
thx @artemklevtsov

**Comment by sckott** [comment]
changes in 864d2b3 and 95e1deb
